from termcolor import colored
import time
import random

troll = [colored("Тролль измазал стены вашей кровью.", "red"), colored("Тролль раздавил вас в лепёшку.", "red"),
         colored("Вы были съедены Троллем.", "red"), colored("Ваша душа была освобождена благодаря Троллю", "red"),
         colored("Тролль сплющил вас своими огромными толстыми руками.", "red"), ]

print(colored("Вас приветствует", "blue"), colored("Dungeon Quest.", "red"))
time.sleep(0.3)
print(colored("Для того, чтобы начать игру, нажмите", "blue"), '\033[95mEnter.\033[0m')
StartGame = str(input())
if StartGame == "":
    time.sleep(0.5)
    print(colored("Ваше снаряжение:", "green"))
    print("")
    print(colored("Лук", "magenta"))
    print(colored("Меч", "magenta"))
    print(colored("Маленький ножик", "magenta"))
    print(colored("Щит", "magenta"))
    print("")
    time.sleep(0.7)
    print(colored("Вы находитесь возле входа в подземелье.", "cyan"))
    time.sleep(1)
    print(colored("Что вы будете делать?", "cyan"))
    time.sleep(0.5)
    print("")
    print(colored("1) Отступить.", "green"))
    print(colored("2) Войти в подземелье.", "green"))
    print("")
    print(colored("Ваш выбор?", "cyan"))
    you = int(input())
    if you == 1:
        time.sleep(1)
        print("")
        print(colored("Вы отступили назад.", "cyan"))
        time.sleep(0.5)
        print(colored("Game Over.", "red"))

    elif you == 2:
        time.sleep(1)
        print("")
        print(colored("Отлично, вы вошли в подземелье.", "cyan"))
        time.sleep(1)
        print(colored("Впереди тёмный коридор", "cyan"))
        time.sleep(1)
        print(colored("Вы ничего не можете разглядеть, но у вас есть факел.", "cyan"))
        time.sleep(2)
        print(colored("Вы хотите зажечь его?", "cyan"))
        time.sleep(0.5)
        print("")
        print(colored("1) Зажечь", "green"))
        print(colored("2) Не зажигать, идти в темноте.", "green"))
        print("")
        fakel = int(input())
        if fakel == 1:
            time.sleep(1)
            print("")
            print(colored("Вы зажгли факел.", "cyan"))
            time.sleep(1)
            print("")
            print(colored("Вы видите перед собой 2 прохода:", "cyan"))
            time.sleep(1)
            print(colored("Какой из них вы выберете?", "cyan"))
            time.sleep(0.5)
            print("")
            print(colored("1) Левый", "green"))
            print(colored("2) Правый", "green"))
            print("")
            tunnel = int(input())
            time.sleep(1)
            if tunnel == 2:
                print(colored("Осторожно! Впереди", "cyan"), colored("Орк", "red") + colored("!", "cyan"))
                time.sleep(1)
                print(colored("Орк атакует вас!", "red"))
                time.sleep(2)
                print("")
                print(colored("Чтобы отразить атаку, используйте", "cyan"), (colored("Щит", "blue")))
                shield = input()
                if (shield == "щит") or (shield == "Щит"):
                    time.sleep(1)
                    print(colored("Вы отразили атаку, отлично!", "cyan"))
                    time.sleep(1)
                    print(colored("Чтобы атоковать, выберете подходящий предмет:", "cyan"))
                    time.sleep(2)
                    print(colored("1) Лук", "magenta"))
                    print(colored("2) Меч", "magenta"))
                    print(colored("3) Маленький ножик", "magenta"))
                    predmet = int(input())
                    if predmet == 1:
                        print(colored("Вы выбрали лук", "cyan"))
                        time.sleep(1)
                        print(colored("Орк уже рядом!", "cyan"))
                        time.sleep(2)
                        print(colored("Вы не успели выстрелить, орк пронзил вас клинком.", "cyan"))
                        time.sleep(1)
                        print("")
                        print(colored("Game Over.", "red"))
                    elif predmet == 3:
                        print(colored("Вы выбрали Маленький ножик", "cyan"))
                        time.sleep(1)
                        print(colored("Орк уже возле вас!", "cyan"))
                        time.sleep(2)
                        print(colored(
                            "Вы успели достать нож и нанесли удар наступающему орку, но он тоже успел ранить вас.",
                            "cyan"))
                        time.sleep(2)
                        print(colored("Вы убили друг друга", "cyan"))
                        time.sleep(1)
                        print("")
                        print(colored("Game Over.", "red"))
                    elif predmet == 2:
                        print(colored("Вы выбрали Меч", "cyan"))
                        time.sleep(1)
                        print(colored("Орк уже на подходе!", "cyan"))
                        time.sleep(1)
                        print(colored("Вы успели схватить меч и отрубили головёшку Орку!", "cyan"))
                        time.sleep(1)
                        print("")
                        print(colored("Отлично!", "cyan"))
                        print("")
                        time.sleep(2)
                        print(colored("Аккуратно, переступая через останки Орка, вы двинулись дальше...", "cyan"))
                        time.sleep(4)
                        print(colored("Что происходит?", "blue"))
                        time.sleep(1)
                        print(colored("О нет! Дверь позади вас захлопнулась! Потолок начал опускаться...", "blue"))
                        time.sleep(3)
                        print(colored("Вы дожны найти способ выжить!", "blue"))
                        print("")
                        print(colored("Искать?", "cyan"))
                        print("")
                        time.sleep(0.5)
                        print(colored("1) Да", "green"))
                        print(colored("2) Нет", "green"))
                        alife = int(input())
                        if alife == 2:
                            print(colored("Потолок уже совсем низко!", "blue"))
                            time.sleep(2)
                            print(colored("Вы не успели найти выход.", "blue"))
                            time.sleep(2)
                            print("")
                            print(colored("Game Over.", "red"))
                        elif alife == 1:
                            print(colored("Вы осматриваете комнату, помните, нужно действовать быстро", "blue"))
                            time.sleep(1)
                            print(colored("Вы видите отверстие в стене.", "cyan"))
                            time.sleep(1)
                            print(colored("Влесть в него?", "cyan"))
                            time.sleep(0.5)
                            print("")
                            print(colored("1) Да", "green"))
                            print(colored("2) Нет", "green"))
                            print("")
                            otverst = int(input())
                            if otverst == 2:
                                print(colored("Потолок уже совсем низко!", "blue"))
                                time.sleep(1)
                                print(colored("Вы не успели вылезти из ловушки.", "blue"))
                                time.sleep(1)
                                print(colored("Теперь вы годитесь для начинки для котлет.", "blue"))
                                time.sleep(2)
                                print("")
                                print(colored("Game Over.", "red"))
                            elif otverst == 1:
                                print(colored("Вы просачились в стену.", "blue"))
                                time.sleep(2)
                                print(colored("Проползя дальше, пол под вами обрушился...", "blue"))
                                time.sleep(2)
                                print(colored("Вы оказались в той самой комнате с двумя проходами.", "blue"))
                                time.sleep(2)
                                print(colored("Войти ли в левый проход?", "blue"))
                                time.sleep(0.5)
                                print("")
                                print(colored("1) Да", "green"))
                                print(colored("2) Нет", "green"))
                                print("")
                                lev = int(input())
                                time.sleep(2)
                                if lev == 2:
                                    print(colored("Вы вышли из подземелья.", "blue"))
                                    time.sleep(1)
                                    print(colored("Game Over.", "red"))
                                elif lev == 1:
                                    print(colored("Вы вошли в левый проход.", "blue"))
                                    time.sleep(2)
                                    print(colored("Перед вами 2 двери.", "cyan"))
                                    time.sleep(2)
                                    print(colored("В какую зайдёте?", "cyan"))
                                    time.sleep(0.5)
                                    print("")
                                    print(colored("1) Позолоченная дверь", "green"))
                                    print(colored("2) Простая дверь в пыли", "green"))
                                    print("")
                                    d = int(input())
                                    if d == 1:
                                        time.sleep(1)
                                        print("")
                                        print(colored("Вы вошли в позолоченную дверь.", "cyan"))
                                        time.sleep(2)
                                        print(colored("Аккуратно, по среди комнаты сидит огромный тролль!", "blue"))
                                        time.sleep(3)
                                        print(colored("Тролль охраняет сундук с неизвестными предметами.", "cyan"))
                                        time.sleep(3)
                                        print(colored("Похоже он спит...", "blue"))
                                        time.sleep(1)
                                        print(colored("Погасите факел, чтобы не разбудить тролля!", "blue"))
                                        time.sleep(0.5)
                                        print("")
                                        print(colored("1) Погасить.", "green"))
                                        print(colored("2) Не тушить факел.", "green"))
                                        print("")
                                        fakel_1 = int(input())
                                        time.sleep(1)
                                        if fakel_1 == 2:
                                            print("")
                                            print(colored("Вы разбудили тролля!", "blue"))
                                            t = random.choice(troll)
                                            print(t)
                                            time.sleep(1)
                                            print("")
                                            print(colored("Game over.", "red"))
                                        elif fakel_1 == 1:
                                            print("")
                                            print(colored("Отлично, факел погас, теперь тролль не проснётся.", "cyan"))
                                            time.sleep(3)
                                            print(colored("Открыть сундук?", "blue"))
                                            print("")
                                            time.sleep(0.5)
                                            print(colored("1) Да", "green"))
                                            print(colored("2) Нет", "green"))
                                            chest = int(input())
                                            if chest == 1:
                                                time.sleep(0.4)
                                                print("")
                                                print(colored("Вы решили открыть сундук...", "blue"))
                                                time.sleep(3)
                                                print("")
                                                print(colored("О нет! Вы разбудили тролля!", "blue"))
                                                time.sleep(2)
                                                t = random.choice(troll)
                                                print(t)
                                                time.sleep(1)
                                                print("")
                                                print(colored("Game over.", "red"))
                                            elif chest == 2:
                                                time.sleep(0.4)
                                                print("")
                                                print(colored("Вы не стали открывать сундук, а вышли из комнаты.",
                                                              "blue"))
                                                time.sleep(2)
                                                print(colored("Зайти в другую комнату?", "blue"))
                                                time.sleep(0.5)
                                                print("")
                                                print(colored("1) Да", "green"))
                                                print(colored("2) Нет", "green"))
                                                print("")
                                                dver = int(input())
                                                time.sleep(1)
                                                if dver == 2:
                                                    print(colored("Вы решили выйти из подземелья...", "blue"))
                                                    time.sleep(3)
                                                    print(colored("Вы ушли с пустыми руками, но зато живьём.", "blue"))
                                                    time.sleep(2)
                                                    print(colored("Вы выжили. Игра окончена.", "blue"))
                                                elif dver == 1:
                                                    print(colored("Вы вошли в комнату с пыльной дверью.", "blue"))
                                                    time.sleep(2)
                                                    print(colored("Вау, сколько сокровищ!", "blue"))
                                                    time.sleep(2)
                                                    print(colored("Вы не ушли с пустыми руками!", "blue"))
                                                    time.sleep(1)
                                                    print(colored("Замечательно!", "yellow"))
                                    elif d == 2:
                                        print(colored("Вы вошли в комнату с пыльной дверью.", "blue"))
                                        time.sleep(2)
                                        print(colored("Вау, сколько сокровищ!", "blue"))
                                        time.sleep(2)
                                        print(colored("Вы не ушли с пустыми руками!", "blue"))
                                        time.sleep(1)
                                        print(colored("Замечательно!", "yellow"))
                        else:
                            print(colored("Потолок уже ниже вашего роста!", "blue"))
                            time.sleep(2)
                            print(colored("Вы не успели выбраться.", "blue"))
                            time.sleep(2)
                            print("")
                            print(colored("Game Over.", "red"))
                    else:
                        print(colored("Вы не успели отразить атаку.", "cyan"))
                        time.sleep(2)
                        print(colored("Орк убил вас.", "cyan"))
                        time.sleep(1)
                        print("")
                        print(colored("Game Over.", "red"))
                else:
                    print(colored("Вы не успели отразить атаку.", "cyan"))
                    time.sleep(2)
                    print(colored("Орк убил вас.", "cyan"))
                    time.sleep(1)
                    print("")
                    print(colored("Game Over.", "red"))
            elif tunnel == 1:
                print(colored("Вы вошли в левый проход.", "blue"))
                time.sleep(2)
                print(colored("Перед вами 2 двери.", "cyan"))
                time.sleep(2)
                print(colored("В какую зайдёте?", "cyan"))
                time.sleep(0.5)
                print("")
                print(colored("1) Позолоченная дверь", "green"))
                print(colored("2) Простая дверь в пыли", "green"))
                print("")
                d = int(input())
                if d == 1:
                    time.sleep(1)
                    print("")
                    print(colored("Вы вошли в позолоченную дверь.", "cyan"))
                    time.sleep(2)
                    print(colored("Аккуратно, по среди комнаты сидит огромный тролль!", "blue"))
                    time.sleep(3)
                    print(colored("Тролль охраняет сундук с неизвестными предметами.", "cyan"))
                    time.sleep(3)
                    print(colored("Похоже он спит.", "blue"))
                    time.sleep(2)
                    print(colored("Погасите факел, чтобы не разбудить тролля!", "blue"))
                    time.sleep(0.5)
                    print("")
                    print(colored("1) Погасить.", "green"))
                    print(colored("2) Не тушить факел.", "green"))
                    print("")
                    fakel_1 = int(input())
                    if fakel_1 == 2:
                        print("")
                        print(colored("Вы разбудили тролля!", "blue"))
                        time.sleep(2)
                        t = random.choice(troll)
                        print(t)
                        time.sleep(1)
                        print("")
                        print(colored("Game over.", "red"))
                    elif fakel_1 == 1:
                        print("")
                        print(colored("Отлично, факел погас, теперь тролль не проснётся.", "cyan"))
                        time.sleep(3)
                        print(colored("Открыть сундук?", "blue"))
                        time.sleep(0.5)
                        print("")
                        print(colored("1) Да", "green"))
                        print(colored("2) Нет", "green"))
                        chest = int(input())
                        if chest == 1:
                            time.sleep(0.5)
                            print("")
                            print(colored("Вы решили открыть сундук...", "blue"))
                            time.sleep(3)
                            print("")
                            print(colored("О нет! Вы разбудили тролля!", "blue"))
                            time.sleep(2)
                            t = random.choice(troll)
                            print(t)
                            time.sleep(1)
                            print("")
                            print(colored("Game over.", "red"))
                        elif chest == 2:
                            time.sleep(0.5)
                            print("")
                            print(colored("Вы не стали открывать сундук, а вышли из комнаты.", "blue"))
                            time.sleep(3)
                            print(colored("Зайти в другую комнату?", "blue"))
                            time.sleep(0.5)
                            print("")
                            print(colored("1) Да", "green"))
                            print(colored("2) Нет", "green"))
                            print("")
                            dver = int(input())
                            if dver == 2:
                                time.sleep(0.5)
                                print(colored("Вы решили выйти из подземелья.", "blue"))
                                time.sleep(2)
                                print(colored("Вы ушли с пустыми руками, но зато живьём.", "blue"))
                                time.sleep(1)
                                print(colored("Вы выжили. Игра окончена.", "blue"))
                            elif dver == 1:
                                time.sleep(0.5)
                                print(colored("Вы вошли в комнату с пыльной дверью.", "blue"))
                                time.sleep(2)
                                print(colored("Вау, сколько сокровищ!", "blue"))
                                time.sleep(1)
                                print(colored("Вы не ушли с пустыми руками!", "blue"))
                                time.sleep(1)
                                print(colored("Замечательно!", "yellow"))
        elif fakel == 2:
            time.sleep(1)
            print("")
            print(colored("Вы не стали зажигать факел.", "cyan"))
            time.sleep(2)
            print(colored("Немного погодя вы запнулись в темноте, из-за чего вас услышал Орк", "blue"))
            time.sleep(3)
            print(colored("Орк убил вас так быстро, что вы не успели опомниться.", "red"))
            time.sleep(2)
            print(colored("Game Over.", "red"))
